### ISSUE TITLE
Pre-trained models

### ISSUE THREAD

**Issue by RanBenIzhak** [cuiziteng/ICCV_MAET#2]
Excellent work!
Thanks you for providing the code.

In the pre trained models section, the google drive links for:
MAET-COCO
and
MAET-EXDark (77.7) 

Point to the same file.

could you please fix the links for the weights on google drive?

**Comment by RanBenIzhak** [comment]
Thank you for the fast reply!

I did not manage to load the pre-trained model, with the following error code - 

(tools\test.py - line 164  -   checkpoint = load_checkpoint(model, args.checkpoint, map_location='cpu')

Traceback (most recent call last):
  File "/home/~/.conda/envs/MAET/lib/python3.7/site-packages/torch/serialization.py", line 585, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/~/.conda/envs/MAET/lib/python3.7/site-packages/torch/serialization.py", line 755, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.


For the model argument i was giving the "MAET-EXDark/data.pkl" path.
Any idea on how to solve the issue?

Thanks!
